# Generated by Django 3.1 on 2020-09-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Errors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Дата')),
                ('machine_id', models.PositiveSmallIntegerField(verbose_name='ID Станка')),
                ('error_id', models.CharField(max_length=20, verbose_name='ID Ошибки')),
            ],
            options={
                'verbose_name': 'Ошибка',
                'verbose_name_plural': 'Ошибки',
                'db_table': 'errors_machine',
            },
        ),
        migrations.CreateModel(
            name='Failures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Дата')),
                ('machine_id', models.PositiveSmallIntegerField(verbose_name='ID Станка')),
                ('failure_id', models.CharField(max_length=20, verbose_name='ID Поломки')),
            ],
            options={
                'verbose_name': 'Поломка',
                'verbose_name_plural': 'Поломки',
                'db_table': 'failures',
            },
        ),
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.PositiveSmallIntegerField(verbose_name='ID Станка')),
                ('model', models.CharField(max_length=20, verbose_name='ID Модели')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Возраст')),
            ],
            options={
                'verbose_name': 'станок',
                'verbose_name_plural': 'станки',
                'db_table': 'machines',
            },
        ),
        migrations.CreateModel(
            name='Maint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Дата')),
                ('machine_id', models.PositiveSmallIntegerField(verbose_name='ID Станка')),
                ('comp_id', models.CharField(max_length=20, verbose_name='ID Ремонта')),
            ],
            options={
                'verbose_name': 'Ремонт',
                'verbose_name_plural': 'Ремонты',
                'db_table': 'maint_machine',
            },
        ),
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Дата')),
                ('machine_id', models.PositiveSmallIntegerField(verbose_name='ID Станка')),
                ('volt', models.FloatField(verbose_name='Напряжение')),
                ('rotate', models.FloatField(verbose_name='Поворот')),
                ('pressure', models.FloatField(verbose_name='Давление')),
                ('vibration', models.FloatField(verbose_name='Вибрация')),
            ],
            options={
                'verbose_name': 'телеметрия',
                'verbose_name_plural': 'телеметрия',
                'db_table': 'telemetry',
            },
        ),
    ]
