# Generated by Django 3.1 on 2020-09-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictive', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machines',
            name='model_id',
        ),
        migrations.AddField(
            model_name='machines',
            name='model',
            field=models.CharField(default=1, max_length=20, verbose_name='ID Модели'),
            preserve_default=False,
        ),
    ]
