# Generated by Django 3.1 on 2020-09-07 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predictive', '0002_auto_20200907_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlalgorithm',
            name='parent_endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictive.endpoint', verbose_name='Конечная точка'),
        ),
        migrations.AlterField(
            model_name='mlalgorithmstatus',
            name='parent_mlalgorithm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='predictive.mlalgorithm', verbose_name='Алгоритм'),
        ),
        migrations.AlterField(
            model_name='mlrequest',
            name='parent_mlalgorithm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictive.mlalgorithm', verbose_name='Алгоритм'),
        ),
    ]
