# Generated by Django 3.1 on 2020-09-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictive', '0002_auto_20200905_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Дата')),
                ('machine_id', models.PositiveSmallIntegerField(verbose_name='ID Станка')),
                ('volt', models.FloatField(verbose_name='Напряжение')),
                ('rotate', models.FloatField(verbose_name='Поворот')),
                ('pressure', models.FloatField(verbose_name='Давление')),
                ('vibration', models.FloatField(verbose_name='Вибрация')),
            ],
            options={
                'verbose_name': 'телеметрия',
                'verbose_name_plural': 'телеметрия',
                'db_table': 'telemetry',
            },
        ),
    ]
