# Generated by Django 3.1 on 2020-09-07 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('firstName', models.CharField(max_length=50, verbose_name='Имя')),
                ('middleName', models.CharField(max_length=50, verbose_name='Отчество')),
                ('numberPhone', models.PositiveSmallIntegerField(verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.SlugField(verbose_name='Станок')),
            ],
            options={
                'verbose_name': 'Станок',
                'verbose_name_plural': 'Станки',
                'db_table': 'machine',
            },
        ),
        migrations.CreateModel(
            name='MachineCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machineCondition', models.CharField(max_length=50, verbose_name='Cостояние станка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('parentMachine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.machine', verbose_name='Станок')),
            ],
            options={
                'verbose_name': 'Состояние станка',
                'verbose_name_plural': 'Состояния станков',
                'db_table': 'machine_condition',
            },
        ),
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacture', models.CharField(max_length=30, verbose_name='Цех')),
            ],
            options={
                'verbose_name': 'Цех',
                'verbose_name_plural': 'Цеха',
                'db_table': 'manufacture',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'db_table': 'position',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('malfunction', models.CharField(max_length=100, verbose_name='Неисправность')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.machine', verbose_name='Станок')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.employee', verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'db_table': 'request',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=50, verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
                'db_table': 'specialty',
            },
        ),
        migrations.CreateModel(
            name='TypeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestType', models.CharField(max_length=30, verbose_name='Тип заявки')),
            ],
            options={
                'verbose_name': 'Тип заявки',
                'verbose_name_plural': 'Типы заявок',
                'db_table': 'type_request',
            },
        ),
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.machine', verbose_name='Станок')),
                ('manufacture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.manufacture', verbose_name='Цех')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee', verbose_name='Рабочий')),
            ],
            options={
                'verbose_name': 'Рабочее место',
                'verbose_name_plural': 'Рабочие места',
                'db_table': 'workplace',
            },
        ),
        migrations.CreateModel(
            name='RequestStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='Статус заявки')),
                ('owner', models.CharField(max_length=128, verbose_name='Автор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('parentRequest', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.request', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Статус завки',
                'verbose_name_plural': 'Статусы заявки',
                'db_table': 'request_status',
            },
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateStartRepair', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала ремонта')),
                ('repairWorker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee', verbose_name='Рабочий')),
                ('requestRepair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.request', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Ремонт',
                'verbose_name_plural': 'Ремонты',
                'db_table': 'repair',
            },
        ),
        migrations.CreateModel(
            name='MachineStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.machine', verbose_name='Станок')),
                ('machineCondition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.machinecondition', verbose_name='Состояние станка')),
                ('repair', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.repair', verbose_name='Ремонт')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.workplace', verbose_name='Рабочее место')),
            ],
            options={
                'verbose_name': 'Статус работы станка',
                'verbose_name_plural': 'Статусы работы станка',
                'db_table': 'machine_status',
            },
        ),
        migrations.CreateModel(
            name='FeatureMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featureName', models.CharField(max_length=100, verbose_name='Название характеристики')),
                ('featureDescription', models.TextField(blank=True, verbose_name='Описание характеристики')),
                ('featureValue', models.PositiveSmallIntegerField(verbose_name='Значание характеристики')),
                ('machine', models.ManyToManyField(to='main.Machine')),
            ],
            options={
                'verbose_name': 'Характеристика станка',
                'verbose_name_plural': 'Характеристики станков',
                'db_table': 'feature_machine',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.position', verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='employee',
            name='specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.specialty', verbose_name='Специальность'),
        ),
    ]
